// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rreivetyyrzhhbuutosv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyZWl2ZXR5eXJ6aGhidXV0b3N2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NDE2ODMsImV4cCI6MjA2MDQxNzY4M30.EkHpMnjV38jIHilYhWblzVhLMeQxvY8Dpicu34peq90";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);